export const PAGINATION = {
  DEFAUT_PAGE_INDEX: 1,
  DEFAULT_PAGE_SIZE: 10
}

export const DATE_RANGE_SELECT = {
  MAX_YEAR: 2100,
  MIN_YEAR: 1930
}

export const OAUTH_LOGIN_ERROR_MESSAGE = 'ACCOUNT_NOT_EXIST_IN_SYSTEM'
